name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        build: [linux, macos, win64]

        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: ggez-bouncing-ball
            archive: .tar.gz
            type: application/gzip
          - build: macos
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: ggez-bouncing-ball
            archive: .tar.gz
            type: application/gzip
          - build: win64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: ggez-bouncing-ball.exe
            archive: .zip
            type: application/zip
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install packages (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -yq --no-install-suggests --no-install-recommends install libx11-dev libxi-dev libgl1-mesa-dev libasound2-dev libudev-dev
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust || 'stable' }}
          target: ${{ matrix.target }}
          profile: minimal
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}